// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
    "time"
	"github.com/google/uuid"
    "gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
    ID        uuid.UUID      `gorm:"column:id;type:UUID;primaryKey";default:uuid.New()" json:"id"` // Use TEXT for UUID
    FullName  string         `gorm:"column:full_name;type:TEXT;not null" json:"full_name"` // Use TEXT for strings
    Phone     *string        `gorm:"column:phone;type:TEXT" json:"phone"` // Use TEXT for strings
    Gender    *string        `gorm:"column:gender;type:TEXT" json:"gender"` // Use TEXT for strings
    Email     string         `gorm:"column:email;type:TEXT;not null" json:"email"` // Use TEXT for strings
    Password  string         `gorm:"column:password;type:TEXT;not null" json:"password"` // Use TEXT for strings
    CreatedAt time.Time      `gorm:"column:created_at;type:DATETIME;not null" json:"created_at"` // Use DATETIME for timestamps
    UpdatedAt *time.Time     `gorm:"column:updated_at;type:DATETIME" json:"updated_at"` // Use DATETIME for timestamps
    DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:DATETIME" json:"deleted_at"` // Use DATETIME for timestamps
}

// TableName User's table name
func (*User) TableName() string {
    return TableNameUser
}